module "this" {
  source                    = "../../"
  vpc_id                    = "${local.vpc_id}"
  environment               = "${local.environment}"
  lb_subnet_ids             = "${local.lb_subnet_ids}"
  listener_certificate_arn  = "${local.listener_certificate_arn}"
  lb_logs_s3_bucket_name    = "${local.lb_logs_s3_bucket_name}"
  lb_tg_health_check        = "${local.tg_health_check}"
  route53_private_zone_id   = "${local.route53_private_zone_id}"
  cluster_role              = "${local.cluster_role}"
  commonEC2_policy_arn      = "${local.commonEC2_policy_arn}"
  ssm_policy_arn            = "${local.ssm_policy_arn}"
  image_owner               = "${local.image_owner}"
  launch_template_overrides = "${local.launch_template_overrides}"
  user_data                 = ""
  asg_max_capacity          = "${local.asg_max_capacity}"
  asg_min_capacity          = "${local.asg_min_capacity}"
  image_id                  = "${local.image_id}"
  user_data                 = "${local.user_data}"
  asg_vpc_zone_identifier   = "${local.asg_vpc_zone_identifier}"
  mchjob_redis_sg_id        = "${local.redis_sg_id}"
  culsrch_vpce_sg_id        = "${local.culsrch_vpce_sg_id}"

  cntcms_vpce_sg_id = "${local.cntcms_vpce_sg_id}"

  cntres_vpce_sg_id = "${local.cntres_vpce_sg_id}"

  recsys_vpce_sg_id  = "${local.recsys_vpce_sg_id}"
  recqry_vpce_sg_id  = "${local.recqry_vpce_sg_id}"
  paywlt_vpce_sg_id  = "${local.paywlt_vpce_sg_id}"
  ptswlt_vpce_sg_id  = "${local.ptswlt_vpce_sg_id}"
  usracid_vpce_sg_id = "${local.usracid_vpce_sg_id}"
  acdsr_vpce_sg_id   = "${local.acdsr_vpce_sg_id}"
  cntp13n_vpce_sg_id = "${local.cntp13n_vpce_sg_id}"
  cnmsrch_vpce_sg_id = "${local.cnmsrch_vpce_sg_id}"
  trpiapi_vpce_sg_id = "${local.trpiapi_vpce_sg_id}"
  # ugcboo_vpce_sg_id = "${local.ugcboo_vpce_sg_id}"
  xpesrch_vpce_sg_id = "${local.xpesrch_vpce_sg_id}"
  locgs_vpce_sg_id   = "${local.locgs_vpce_sg_id}"
  srssrch_vpce_sg_id = "${local.srssrch_vpce_sg_id}"
  # aprsr_vpce_sg_id   = "${local.aprsr_vpce_sg_id}"
  mchdata_mongo_sg_id  = "${local.mongo_sg_id}"

  fprinv_vpce_sg_id = "${local.fprinv_vpce_sg_id}"
  vcpint_vpce_sg_id = "${local.vcpint_vpce_sg_id}"

  mchitmd_lb_sg_id = "${local.mchitmd_lb_sg_id}"

  mchcntr_lb_sg_id = "${local.mchcntr_lb_sg_id}"
  mchdata_lb_sg_id = "${local.mchdata_lb_sg_id}"
  mchitmp_lb_sg_id = "${local.mchitmp_lb_sg_id}"
  receive_wait_time_seconds        = "${local.receive_wait_time_seconds}"
  message_retention_seconds        = "${local.message_retention_seconds}"
  visibility_timeout_seconds       = "${local.visibility_timeout_seconds}"
}
